require("vim._core.ui2").enable({})

require("jatobro.options")
require("jatobro.pack")
require("jatobro.telescope")
require("jatobro.lsp")
require("jatobro.autocmds")
require("jatobro.keymaps")
require("jatobro.gitsigns")
require("jatobro.which-key")
require("jatobro.mini")
require("jatobro.todo-comments")
require("jatobro.treesitter")
require("jatobro.conform")
require("jatobro.colorscheme")
